#--------------------------------------------------------------------------------------------------
#                                     General config file
# -------------------------------------------------------------------------------------------------

# Task to be performed
task: "push_soft"
# -----------------------------  Task list ------------------------------------
#
# "pushing_moderate_clutter" - Moderate clutter pushing task
# "push_soft" - Soft object pushing task
# "push_soft_into_rigid" - Soft object pushing into rigid object task

# Run mode for the program
runMode: "MPC_until_completion"
# Valid runModes are:
# "Init_controls"           - Displays the initial controls on repeat.
# "Optimise_once"           - Optimise the trajectory open loop, display the optimised controls and initial controls repeatedly.
# "MPC_until_completion"    - Perform MPC until the task is completed. Display current state of the system.

# Extra testing modes for debugging/generating testing data
# "Generate_test_scenes"          - Generate a set of randomly generated test scenes for the task.
# "Generate_openloop_data"        - Loop through all the test scenes, using current optimiser and perform open loop optimisation tests.
# "Generate_asynchronus_mpc_data" - Loop through all the tests scenes, using current optimiser and perform asyncronus MPC optimisation.
# "Generate_filtering_data"       - Loop through all test scenes and evaluate baseline optimisation with and without filtering.
# "Generate_dynamics_data"        - Loop through 100 CSV files and generate A, B, X, U data over a horizon and save to file.

# Special modes - possibly temporary
# "Analyse_toy_contact"          - Analyse the derivatives in toy example with contact.

taskInitMode: "fromYAML"    # taskInitMode can be, "random", "fromCSV", "fromYAML"
csvRow: 0                 # CSV row to load if taskInitMode is "fromCSV" (0 - 99)

minIter: 3                # Minimum number of iterations to run Optimiser for
maxIter: 10               # Maximum number of iterations to run Optimiser for

async_mpc: true
record: false